import AppKit
import Combine
import UniformTypeIdentifiers
import AVFoundation

/// Polls `TestIsolation.board.changeCount` — the same mechanism Maccy uses —
/// and turns new content into typed `ClipboardItem`s.
final class ClipboardMonitor {

    static let shared = ClipboardMonitor()

    private(set) var isRunning = false
    private var timer: Timer?
    private var lastChangeCount = 0
    private var ignoreUntil = Date.distantPast

    /// Paused from the menu-bar menu; nothing is recorded while true.
    var isPaused = false

    private init() {
        lastChangeCount = TestIsolation.board.changeCount
    }

    // MARK: - Lifecycle

    func start() {
        guard !isRunning else { return }
        isRunning = true
        lastChangeCount = TestIsolation.board.changeCount
        scheduleTimer()
    }

    func stop() {
        isRunning = false
        timer?.invalidate()
        timer = nil
    }

    /// Rebuilds the timer when the user changes the poll interval.
    func restart() {
        guard isRunning else { return }
        timer?.invalidate()
        scheduleTimer()
    }

    private func scheduleTimer() {
        let interval = max(0.05, Double(PreferencesModel.shared.pollIntervalMS) / 1000.0)
        let t = Timer(timeInterval: interval, repeats: true) { [weak self] _ in self?.check() }
        t.tolerance = interval * 0.25
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    /// Ignores the next change, used right after we write to the pasteboard
    /// ourselves so a pasted item doesn't loop back into history.
    func suppressNextCapture() {
        ignoreUntil = Date().addingTimeInterval(1.0)
    }

    private func check() {
        let pb = TestIsolation.board
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard !isPaused, Date() > ignoreUntil else { return }
        guard !shouldIgnore(pb) else { return }
        capture(pb)
    }

    // MARK: - Privacy

    /// Pasteboard types that mean "do not record this".
    /// These are the flags password managers set; honouring them is the single
    /// most important privacy behaviour a clipboard manager has.
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb"
    ]

    private func shouldIgnore(_ pb: NSPasteboard) -> Bool {
        let types = Set((pb.types ?? []).map(\.rawValue))
        if PreferencesModel.shared.respectConcealedTypes,
           !types.isDisjoint(with: Self.concealedTypes) {
            return true
        }
        if let bundle = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           PreferencesModel.shared.ignoredAppList.contains(bundle) {
            return true
        }
        return false
    }

    // MARK: - Capture

    private func capture(_ pb: NSPasteboard) {
        let app = NSWorkspace.shared.frontmostApplication
        let name = app?.localizedName ?? "Unknown"
        let bundle = app?.bundleIdentifier

        // Most specific type wins.
        let item = readImage(pb, name, bundle)
            ?? readFile(pb, name, bundle)
            ?? readRichText(pb, name, bundle)
            ?? readString(pb, name, bundle)

        guard let item else { return }

        // Enforce the size cap on inline text.
        let limit = PreferencesModel.shared.maxTextKB * 1024
        if let t = item.text, t.utf8.count > limit { return }

        DispatchQueue.main.async {
            HistoryStore.shared.add(item)
            // Confirm the capture where the user is already looking. Each kind
            // says the thing that identifies it - "Image 2560 x 1440" rather than
            // "Image", which is no confirmation at all for the one case where you
            // cannot see what you copied.
            // Straight to the state, not through NSApp.delegate: SwiftUI's
            // adaptor puts its OWN SwiftUI.AppDelegate on NSApp, so a cast to
            // this app's AppDelegate is always nil and the call vanished.
            MainActor.assumeIsolated {
                CopyConfirmation.shared.show(item.copyConfirmation(limit: 28))
            }
        }
    }

    // MARK: - Readers

    private func readImage(_ pb: NSPasteboard, _ name: String, _ bundle: String?) -> ClipboardItem? {
        let types = pb.types ?? []
        guard types.contains(.png) || types.contains(.tiff) || types.contains(.jpegType) else { return nil }
        guard let data = pb.data(forType: .png) ?? pb.data(forType: .tiff) ?? pb.data(forType: .jpegType),
              data.count > 200 else { return nil }

        let png = Self.asPNG(data) ?? data
        guard let file = MediaStore.shared.save(png, ext: "png") else { return nil }
        let size = Self.pixelSize(png)
        return ClipboardItem(kind: .image, imageFile: file,
                             sourceApp: bundle, sourceAppName: name,
                             pixelWidth: size?.width, pixelHeight: size?.height)
    }

    #if CLIP_TESTING
    /// Drives the real image reader directly against a pasteboard the probe
    /// has already loaded, so a disk-full/read-only capture failure can be
    /// proved synchronously without waiting on the poll timer.
    func testCaptureImage(_ pb: NSPasteboard) -> ClipboardItem? {
        readImage(pb, "Probe", "app.clip.probe")
    }
    #endif

    private func readFile(_ pb: NSPasteboard, _ name: String, _ bundle: String?) -> ClipboardItem? {
        guard let urls = pb.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
              !urls.isEmpty, urls.allSatisfy(\.isFileURL) else { return nil }

        let paths = urls.map(\.path)
        // Folders, movies and plain files each get their own card.
        let isVideo = urls.allSatisfy { Self.isVideo($0) }
        let isFolder = urls.allSatisfy { Self.isDirectory($0) }
        let kind: ItemKind = isVideo ? .video : (isFolder ? .folder : .file)

        // A video gets a poster frame purely so the card has something to show.
        // It is never what gets pasted — see ClipboardWriter.
        var poster: String?
        var size: (width: Int, height: Int)?
        if isVideo, let first = urls.first, let frame = Self.posterFrame(for: first) {
            poster = MediaStore.shared.save(frame.data, ext: "png")
            size = (frame.width, frame.height)
        }

        return ClipboardItem(kind: kind, text: paths.first, imageFile: poster, filePaths: paths,
                             sourceApp: bundle, sourceAppName: name,
                             pixelWidth: size?.width, pixelHeight: size?.height)
    }

    private func readRichText(_ pb: NSPasteboard, _ name: String, _ bundle: String?) -> ClipboardItem? {
        guard let rtf = pb.data(forType: .rtf) else { return nil }
        let plain = pb.string(forType: .string)
            ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
        guard let plain, !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return ClipboardItem(kind: .richText, text: plain, richText: rtf,
                             sourceApp: bundle, sourceAppName: name)
    }

    private func readString(_ pb: NSPasteboard, _ name: String, _ bundle: String?) -> ClipboardItem? {
        guard let s = pb.string(forType: .string) else { return nil }
        return Self.classify(s, name, bundle)
    }

    /// Decides what a copied string *is*: link, color, path, skill, code, text.
    ///
    /// One function rather than a chain of readers that each fetch the same
    /// string, so the order the tests exercise is the order the app uses.
    /// Testing this through a real pasteboard means racing the system clipboard
    /// against whatever else is running, and a test that flakes gets ignored.
    static func classify(_ s: String, _ name: String, _ bundle: String?) -> ClipboardItem? {
        guard !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }

        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)

        if !trimmed.contains(where: \.isNewline),
           let url = URL(string: trimmed), let scheme = url.scheme?.lowercased(),
           ["http", "https"].contains(scheme), url.host != nil {
            return ClipboardItem(kind: .url, text: trimmed, sourceApp: bundle,
                                 sourceAppName: name, platform: LinkPlatform.detect(trimmed))
        }
        // Stored in the canonical hashed form whatever was copied, so the
        // swatch, the label and the theme maker all read one shape. The item's
        // own text keeps exactly what you copied.
        if let hex = HexColor.normalised(trimmed) {
            return ClipboardItem(kind: .color, text: trimmed, hexColor: hex,
                                 sourceApp: bundle, sourceAppName: name)
        }
        if Self.isEmojiOnly(s) {
            return ClipboardItem(kind: .emoji, text: s, sourceApp: bundle, sourceAppName: name)
        }
        // A path copied as text is still a path. This has to run before the code
        // guess, which happily reads a list of paths as a shell script.
        if let match = PathDetector.classify(s) {
            return ClipboardItem(kind: match.kind, text: match.paths.first,
                                 filePaths: match.paths,
                                 sourceApp: bundle, sourceAppName: name)
        }
        // Design documents are tested FIRST, and it is not a preference of
        // ordering: a DESIGN.md carries front matter with a name and a
        // description, which is precisely the skill signature. Measured over a
        // 74-document corpus the skill detector claimed 64 of them. The design
        // detector is the stricter of the two, so it gets first refusal.
        // Unconditional. This is front matter and a regex - no model, no key,
        // no network - so it is not an AI feature, and filing what you copied
        // into the right tab is not a preference either. It sat in the AI pane
        // behind a switch, which said the opposite of both.
        if let match = ItemClassifier.curatedRole(for: s) {
            return ClipboardItem(kind: .text, text: s, sourceApp: bundle,
                                 sourceAppName: name, title: match.title, role: match.role)
        }
        if let lang = CodeDetector.language(for: s) {
            return ClipboardItem(kind: .code, text: s, sourceApp: bundle,
                                 sourceAppName: name, language: lang)
        }
        return ClipboardItem(kind: .text, text: s, sourceApp: bundle, sourceAppName: name)
    }

    // MARK: - Helpers

    private static func asPNG(_ data: Data) -> Data? {
        guard let img = NSImage(data: data), let tiff = img.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private static func pixelSize(_ data: Data) -> (width: Int, height: Int)? {
        guard let src = CGImageSourceCreateWithData(data as CFData, nil),
              let props = CGImageSourceCopyPropertiesAtIndex(src, 0, nil) as? [CFString: Any],
              let w = props[kCGImagePropertyPixelWidth] as? Int,
              let h = props[kCGImagePropertyPixelHeight] as? Int else { return nil }
        return (w, h)
    }

    /// Grabs a frame ~1s in for the preview. Fails quietly: a video with no
    /// readable track simply gets the generic placeholder card.
    private static func posterFrame(for url: URL) -> (data: Data, width: Int, height: Int)? {
        let asset = AVURLAsset(url: url)
        let generator = AVAssetImageGenerator(asset: asset)
        generator.appliesPreferredTrackTransform = true
        generator.maximumSize = CGSize(width: 800, height: 800)
        let time = CMTime(seconds: 1, preferredTimescale: 600)
        guard let cg = try? generator.copyCGImage(at: time, actualTime: nil) else { return nil }
        let rep = NSBitmapImageRep(cgImage: cg)
        guard let png = rep.representation(using: .png, properties: [:]) else { return nil }
        return (png, cg.width, cg.height)
    }

    private static func isDirectory(_ url: URL) -> Bool {
        (try? url.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory == true
    }

    private static func isVideo(_ url: URL) -> Bool {
        guard let type = UTType(filenameExtension: url.pathExtension) else { return false }
        return type.conforms(to: .movie) || type.conforms(to: .video)
    }

    /// True when the string is only emoji (and whitespace) — a surprisingly
    /// common copy that deserves its own big-glyph card.
    private static func isEmojiOnly(_ s: String) -> Bool {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed.count <= 12 else { return false }
        // Every character must be an emoji cluster. A digit like "1" reports
        // isEmoji == true on its own, so require emoji presentation for
        // single-scalar characters to keep plain numbers out.
        return trimmed.allSatisfy { char in
            guard let first = char.unicodeScalars.first else { return false }
            if char.unicodeScalars.count > 1 {
                return first.properties.isEmoji
            }
            return first.properties.isEmojiPresentation
        }
    }
}

/// Cheap, dependency-free language guessing for code snippets.
///
/// This is deliberately heuristic: the goal is a useful label and a monospace
/// card, not a parser. It errs towards "not code" so ordinary prose is never
/// mislabelled.
enum CodeDetector {

    private static let signatures: [(String, [String])] = [
        ("swift",      ["func ", "let ", "var ", "guard ", "-> ", "@State", "struct ", "import SwiftUI"]),
        ("javascript", ["function ", "const ", "=> ", "console.log", "export ", "require(", "async "]),
        ("python",     ["def ", "import ", "print(", "self.", "elif ", "__init__"]),
        ("json",       ["{\"", "\": ", "\": [", "null,"]),
        ("html",       ["<div", "<span", "<html", "</", "<p>", "<!DOCTYPE"]),
        ("css",        ["{", "}", ": ", "px;", "color:", "margin:", "#"]),
        ("shell",      ["#!/bin", "sudo ", "cd ", "grep ", "echo ", "&& ", "| "]),
        ("sql",        ["SELECT ", "FROM ", "WHERE ", "INSERT INTO", "JOIN "]),
        ("java",       ["public class", "private ", "void ", "System.out"]),
        ("rust",       ["fn ", "let mut", "impl ", "pub fn", "::"])
    ]

    /// Returns a language name when the text looks like code, else nil.
    static func language(for text: String) -> String? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count >= 12 else { return nil }

        // A fenced block is unambiguous.
        if trimmed.hasPrefix("```") {
            let first = trimmed.dropFirst(3).prefix { !$0.isNewline }
            let name = String(first).trimmingCharacters(in: .whitespaces).lowercased()
            return name.isEmpty ? "code" : name
        }

        // Otherwise require real structural evidence, not one stray brace.
        let lines = trimmed.components(separatedBy: .newlines)
        let indented = lines.filter { $0.hasPrefix("  ") || $0.hasPrefix("\t") }.count
        let symbols = trimmed.filter { "{}[]();<>=".contains($0) }.count
        let density = Double(symbols) / Double(max(trimmed.count, 1))

        var best: (String, Int)?
        for (lang, tokens) in signatures {
            let hits = tokens.filter { trimmed.contains($0) }.count
            if hits > (best?.1 ?? 0) { best = (lang, hits) }
        }

        guard let (lang, hits) = best else { return nil }
        let structural = (lines.count > 1 && indented > 0) || density > 0.045
        guard hits >= 2, structural else { return nil }
        return lang
    }
}

extension NSPasteboard.PasteboardType {
    /// `public.jpeg` — AppKit exposes no built-in constant for it.
    static let jpegType = NSPasteboard.PasteboardType("public.jpeg")
}
