#!/usr/bin/env python3
"""Regenerate every measured number quoted in the docs, from the source of
truth on disk, and write them between marker comments in README.md and
START-HERE.md.

Why this exists: an audit on 04/09/2026 found README, START-HERE and
ARCHITECTURE quoting three different assertion counts and two different
Swift line counts for the same codebase, because someone typed a number by
hand after running the suite once and nobody updated it since. A hand-typed
number rots the moment the code moves. This script is the only place a count
is allowed to be produced; every doc pulls from it.

What it counts, and why that definition:
  - Swift lines: `wc -l` over every `*.swift` file under Clip/Clip/, which is
    the actual shipped source tree. `.trash/` is never a source tree.
  - qa-probe assertion call sites: every call to the `check(` helper in
    qa-probe.py, minus its own `def check(...)` line. This is a structural
    count of the suite as written, not a run result - a run result (passed /
    failed / skipped) changes with the code under test and the machine it
    runs on, so it belongs in a probe's own output, never in a doc.
  - security-probe assertion call sites: the same `check(` count in
    security-probe.py.
  - silent-guard gate coverage: how many functions the qa-probe.py
    `run_m4_silent_paths` "NO SILENT GUARDS" gate actually audits (the
    `AUDITED` list), against the total function count in the Swift tree, plus
    how many `try?` sites and bare `guard ... else { return }` sites exist
    outside that gate. The gate covers a named, small list on purpose (see
    that function's docstring); the doc must say so precisely instead of
    implying a codebase-wide rule.

Usage:
    python3 docs/generate-counts.py            # print the measured numbers
    python3 docs/generate-counts.py --write    # also rewrite the doc markers
    python3 docs/generate-counts.py --check    # exit non-zero if the
                                                # checked-in COUNTS blocks
                                                # differ from a fresh
                                                # computation; prints the diff

Run it after any change to qa-probe.py, security-probe.py, the Swift tree,
or the AUDITED list, and before quoting a count anywhere. Never hand-edit a
number between the COUNTS markers - it will be overwritten, and it will be
wrong until you run this.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # Clip/


def count_swift_lines():
    total = 0
    files = 0
    for path in (ROOT / "Clip").rglob("*.swift"):
        if ".trash" in path.parts:
            continue
        total += sum(1 for _ in path.open(encoding="utf-8", errors="ignore"))
        files += 1
    return total, files


def count_check_calls(py_file):
    src = (ROOT / py_file).read_text(encoding="utf-8", errors="ignore")
    calls = len(re.findall(r"\bcheck\(", src))
    defs = len(re.findall(r"^def check\(", src, re.M))
    return calls - defs


def count_functions():
    pat = re.compile(
        r"^\s*(?:private |internal |fileprivate |public |static )*func \w"
    )
    total = 0
    for path in (ROOT / "Clip").rglob("*.swift"):
        if ".trash" in path.parts:
            continue
        for line in path.open(encoding="utf-8", errors="ignore"):
            if pat.match(line):
                total += 1
    return total


def count_try_optional():
    total = 0
    for path in (ROOT / "Clip").rglob("*.swift"):
        if ".trash" in path.parts:
            continue
        src = path.read_text(encoding="utf-8", errors="ignore")
        total += len(re.findall(r"\btry\?", src))
    return total


def count_audited_functions():
    src = (ROOT / "qa-probe.py").read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"AUDITED = \[(.*?)\n    \]", src, re.S)
    if not m:
        return 0
    return len(re.findall(r'\("Clip/', m.group(1)))


def measure():
    swift_lines, swift_files = count_swift_lines()
    qa_asserts = count_check_calls("qa-probe.py")
    sec_asserts = count_check_calls("security-probe.py")
    functions = count_functions()
    audited = count_audited_functions()
    try_opt = count_try_optional()
    return {
        "swift_lines": swift_lines,
        "swift_files": swift_files,
        "qa_asserts": qa_asserts,
        "sec_asserts": sec_asserts,
        "functions": functions,
        "audited_functions": audited,
        "try_optional": try_opt,
    }


COUNTS_START = "<!-- COUNTS:START (generated by docs/generate-counts.py - do not hand-edit) -->"
COUNTS_END = "<!-- COUNTS:END -->"


def render(m):
    return (
        f"{COUNTS_START}\n"
        f"**~{m['swift_lines']:,} lines of Swift** across {m['swift_files']} files, "
        f"**{m['qa_asserts']:,} behaviour-assertion call sites** in `qa-probe.py`, "
        f"**{m['sec_asserts']} security-check call sites** in `security-probe.py`.\n"
        f"{COUNTS_END}"
    )


def block_pattern():
    return re.compile(
        re.escape(COUNTS_START) + r".*?" + re.escape(COUNTS_END), re.S
    )


def write_into(path: Path, block: str):
    text = path.read_text(encoding="utf-8")
    pat = block_pattern()
    if pat.search(text):
        text = pat.sub(block, text)
        path.write_text(text, encoding="utf-8")
        return True
    return False


def extract_block(path: Path):
    """Return the checked-in COUNTS block from path, or None if absent."""
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    m = block_pattern().search(text)
    return m.group(0) if m else None


def check(docs):
    """Regenerate the COUNTS block in memory and diff it against what is
    checked into each doc. Prints a unified diff per doc that differs and
    returns True if every doc matches (green), False on any drift (red)."""
    import difflib

    fresh = render(measure())
    all_match = True
    for doc in docs:
        path = ROOT / doc
        checked_in = extract_block(path)
        if checked_in is None:
            print(f"{doc}: no COUNTS marker found (cannot check)")
            all_match = False
            continue
        if checked_in == fresh:
            print(f"{doc}: COUNTS block matches source (green)")
            continue
        all_match = False
        print(f"{doc}: COUNTS block is stale (red)")
        diff = difflib.unified_diff(
            checked_in.splitlines(keepends=True),
            fresh.splitlines(keepends=True),
            fromfile=f"{doc} (checked in)",
            tofile=f"{doc} (fresh)",
        )
        sys.stdout.writelines(diff)
    return all_match


def main():
    docs = ("README.md", "START-HERE.md")
    if "--check" in sys.argv:
        ok = check(docs)
        sys.exit(0 if ok else 1)

    m = measure()
    print("Measured, from source, %s" % ROOT)
    for k, v in m.items():
        print(f"  {k}: {v:,}" if isinstance(v, int) else f"  {k}: {v}")
    if "--write" in sys.argv:
        block = render(m)
        for doc in docs:
            ok = write_into(ROOT / doc, block)
            print(f"{'wrote' if ok else 'no COUNTS marker in'} {doc}")


if __name__ == "__main__":
    main()
